Fix test_nbr_health.py (#12075)
What is the motivation for this PR?
test_nbr_health.py fails as

No more variables left in this MIB View
On addressing that another error is seen due to Ansible version

KeyError: 'ansible_net_interfaces'
How did you do it?
Fixed both these errors by modifying the test.

How did you verify/test it?
Tested on Arista 7050 platform with dualtor topology.