Fix qos/test_pfc_pause.py for dualtor. (#11986)
What is the motivation for this PR?
qos/test_pfc_pause.py fails for dualtor with the following errors

IndexError: list index out of range
In some rare cases the test continues to run for PG2 and 6.
How did you do it?
Issue 1 is addressed by skipping the test for PG 2 and 6 as none of the the DSCP values map to these PGs in case of dualtor downlink ports. ( Addressed by #12229 )
Issue 2 is addressed by -

Making the randomly selected ToR as active using the fixture toggle_all_simulator_ports_to_rand_selected_tor_m ( addressed by Improve test_pfc_pause to support dualtor #12229 )
Use downlink interface to retrieve lossless priorities as well as DSCP_TO_TC_MAP rather than checking a random interface because qos config is different for uplink and downlink ports in case of dualtor and in this test the traffic flow is from server to server. ( addressed by this PR )
How did you verify/test it?
Verified on Arista-7260 platform using dualtor topology.