[tests-cacl] Add test and validation function (#14704)
Description of PR
This PR addresses the test gap for verifying that control ACL rules loaded into a DUT through acl-loader and a given acl.json.

Summary:
Addresses #10516:

Introduces a test to verify cacl rules are correct after acl-loader loads rules from an acl.json file

Approach
What is the motivation for this PR?
Currently, there is no test to cover verification that cacl rules are correct after acl-loader loads rules from an acl.json file.
This PR intends to address that by adding one.

How did you do it?
Introduced a test, which loads dummy cacl rules from a generated acl.json file, and then validates that the applied rules are the same as is defined in the generated acl.json (i.e. the expected configuration).

How did you verify/test it?
Ran the test on a number of testbeds, confirming that the test correctly reports success in loading and verifying the supplied acl rules.

Sample success:
------------------------------------------------------------------------------------------------------------------------------------------------------------------ live log call -------------------------------------------------------------------------------------------------------------------------------------------------------------------
03:45:03 test_cacl_application.generate_scale_rul L0925 INFO   | Waiting all rules to be applied
PASSED                                                                                                                                                                                                                                                                                                                                       [100%]
---------------------------------------------------------------------------------------------------------------------------------------------------------------- live log teardown -----------------------------------------------------------------------------------------------------------------------------------------------------------------
Sample failure (manually adding a dummy 'TESTFAIL' table to dict of actual tables)
============================================================================================================================================================= short test summary info ==============================================================================================================================================================
FAILED cacl/test_cacl_application.py::test_cacl_acl_loader[str3-8111-01] - Failed: Missing tables in expected: {'TESTFAIL'}, missing tables in actual: set()                                                                                                                                                                                        
===================================================================================================================================================== 1 failed, 1 warning in 955.67s (0:15:55) =====================================================================================================================================================
Sample failure (manually editing expected rules):
>       pytest_assert(
            len(issues) == 0,
            "Issues detected: \n{}".format('\n'.join(issues))
        )
E       Failed: Issues detected:
E       Incorrectly configured ACL rules found:
E       NTP_ACL: The following rules had issues:
E         - RULE_2: Expected IP 20.0.0.3/32 does not match WRONG IP
...
cacl/test_cacl_application.py:1018: Failed
Any platform specific information?
N/A

Supported testbed topology if it's a new test case?
Any topology, as it is with the rest of the cacl testcases, as it leverages common functionality found within the test suite (generation of acl.json, and retrieving show acl rule output).

co-authorized by: jianquanye@microsoft.com